export const RESET_GAME_NUMBERS = 'RESET_GAME_NUMBERS';
export const START_GAME_NUMBERS = 'START_GAME_NUMBERS';
export const START_GAME_NUMBERS_SUCCESS = 'START_GAME_NUMBERS_SUCCESS';
export const GAME_NUMBERS_ERROR = 'GAME_NUMBERS_ERROR';
export const RESET_GAME_NUMBERS_SUCCESS = 'RESET_GAME_NUMBERS_SUCCESS';
